package net.cold.coldsmod.capabilities_and_blessings.Capabilities;

public enum BonusTrigger {
    HURT,

    MELEE_HURT,
    MELEE_HURT_INDIRECT,
    MELEE_CRIT_DIRECT,
    MELEE_CRIT_INDIRECT,
    MELEE_NON_CRIT_DIRECT,
    MELEE_NON_CRIT_INDIRECT,

    PROJECTILE_HURT_BOW,
    PROJECTILE_HURT_BOW_CRIT,
    PROJECTILE_HURT_BOW_NON_CRIT,
    PROJECTILE_LAND_BOW,
    FRIENDLY_FIRE_LIFE_TOUCH,

    PROJECTILE_HURT_CROSSBOW,
    PROJECTILE_HURT_CROSSBOW_CRIT,
    PROJECTILE_HURT_CROSSBOW_NON_CRIT,
    PROJECTILE_LAND_CROSSBOW,

    INDIRECT_RANGE_CRIT,
    INDIRECT_RANGE_NONCRIT,

    OTHER_CRIT,
    OTHER_NONCRIT,

    KILL,

    HEAL,

    DEFEND,
    DAMAGE_TAKE_DAMAGE_EVENT,
    DAMAGE_TAKE_DAMAGE_EVENT_POST,
    DAMAGE_TAKE_ATTACK_EVENT,
    DAMAGE_TAKE_ATTACK_EVENT_PRE,

    ITEM_USE_START_SHIELD,
    ITEM_USE_TICK_SHIELD,
    ITEM_USE_END_SHIELD,

    ITEM_USE_START_BOW,
    ITEM_USE_TICK_BOW,
    ITEM_USE_END_BOW,

    LAND,

    BLESSING_ACTIVATION,

    DEBUFF_APPLIED,

}